### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by avgl-sstraub** [kbastani/neo4j-mazerunner#28]
When running `kbastani/neo4j-graph-analytics:latest` in docker I get an exception during startup:

    Exception in thread "main" java.lang.NoSuchFieldError: IBM_JAVA
        at org.apache.hadoop.security.UserGroupInformation.getOSLoginModuleName(UserGroupInformation.java:337)
        at org.apache.hadoop.security.UserGroupInformation.<clinit>(UserGroupInformation.java:382)
        at org.apache.spark.deploy.SparkHadoopUtil.<init>(SparkHadoopUtil.scala:36)
        at org.apache.spark.deploy.SparkHadoopUtil$.<init>(SparkHadoopUtil.scala:109)
        at org.apache.spark.deploy.SparkHadoopUtil$.<clinit>(SparkHadoopUtil.scala)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:238)
        at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:53)
        at org.mazerunner.core.processor.GraphProcessor.initializeSparkContext(GraphProcessor.java:78)
        at org.mazerunner.core.messaging.Worker.doMain(Worker.java:109)
        at org.mazerunner.core.messaging.Worker.main(Worker.java:60)

The reason for this exception is a conflict between `hadoop-auth-2.4.1.jar` and `hadoop-core-1.2.1.jar`. Both are copied from the `docker/bin/lib` to the classpath in the docker image and both contain the class `org.apache.hadoop.util.PlatformName`, but `hadoop-core` does not declare the field `IBM_JAVA`.

I managed to resolve this issue by simply deleting `hadoop-core-1.2.1.jar` and rebuilding the docker image, though I'm not sure if this break some other part of the application (so far it worked fine for me).

I'm not sure about the structure of this image, but it seems like the projects `org.mazerunner.extension` and `org.mazerunner.spark` have conflicting dependencies yet still they are copied on the same classpath.

If those are two separate programs, maybe you should copy each project and it's dependencies in a separate folder. And if one depends on the other, then you should add the other project as dependency and let Maven resolve the conflicts.

**Comment by avgl-sstraub** [comment]
Well, all I did was delete `docker/bin/lib/hadoop-core-1.2.1.jar`.

The thing is I'm not sure this is a proper fix, it could cause random crashes in other parts of the application. The proper solution would be to resolve the dependency problem between those two projects I've described, but I don't know enough about the structure of this application to reliably fix it myself.

**Comment by kbastani** [comment]
Ok, no worries.
